### PR TITLE
feat(energy): include other SI prefixes for watt hours

### PR DESCRIPTION
**Pull request by furrycatherder**
Although watt-hours are technically non-SI units, they use the same set of prefixes.

### CODE REVIEW

**Comment by furrycatherder** [comment]
@jonahsnider Would you mind reviewing this when you have a moment?

I'd also like to change the `best` array to something like `['GWh', 'MWh', 'KWh', 'Wh']`. I think joules should rather require an explicit conversion because most quantities of energy are expressed in terms of watts.

**Comment by jonahsnider** [comment]
Thanks for the contribution! I'm unfortunately very busy this week, so I might not be able to take a look at the changes until early next week. I'll see if I have time tonight though.

**Comment by furrycatherder** [comment]
Thanks!

**Pull request merged**
